# Generated by Django 5.1 on 2024-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='consenso',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
