# Generated by Django 5.1 on 2024-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0002_member_consenso'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mail_verificata',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
