# Generated by Django 5.1 on 2024-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0003_member_mail_verificata'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
