# Generated by Django 5.1 on 2024-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0004_member_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
