# Generated by Django 5.1 on 2024-08-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0005_alter_member_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail_verificata',
            field=models.BooleanField(null=True),
        ),
    ]
