# Generated by Django 5.1 on 2024-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locandanews', '0006_alter_member_mail_verificata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail_verificata',
            field=models.BooleanField(default=False),
        ),
    ]
